/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Migration } from "./Migration";
import { MigrationCountArgs } from "./MigrationCountArgs";
import { MigrationFindManyArgs } from "./MigrationFindManyArgs";
import { MigrationFindUniqueArgs } from "./MigrationFindUniqueArgs";
import { CreateMigrationArgs } from "./CreateMigrationArgs";
import { UpdateMigrationArgs } from "./UpdateMigrationArgs";
import { DeleteMigrationArgs } from "./DeleteMigrationArgs";
import { MigrationService } from "../migration.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Migration)
export class MigrationResolverBase {
  constructor(
    protected readonly service: MigrationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Migration",
    action: "read",
    possession: "any",
  })
  async _migrationsMeta(
    @graphql.Args() args: MigrationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Migration])
  @nestAccessControl.UseRoles({
    resource: "Migration",
    action: "read",
    possession: "any",
  })
  async migrations(
    @graphql.Args() args: MigrationFindManyArgs
  ): Promise<Migration[]> {
    return this.service.migrations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Migration, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Migration",
    action: "read",
    possession: "own",
  })
  async migration(
    @graphql.Args() args: MigrationFindUniqueArgs
  ): Promise<Migration | null> {
    const result = await this.service.migration(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Migration)
  @nestAccessControl.UseRoles({
    resource: "Migration",
    action: "create",
    possession: "any",
  })
  async createMigration(
    @graphql.Args() args: CreateMigrationArgs
  ): Promise<Migration> {
    return await this.service.createMigration({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Migration)
  @nestAccessControl.UseRoles({
    resource: "Migration",
    action: "update",
    possession: "any",
  })
  async updateMigration(
    @graphql.Args() args: UpdateMigrationArgs
  ): Promise<Migration | null> {
    try {
      return await this.service.updateMigration({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Migration)
  @nestAccessControl.UseRoles({
    resource: "Migration",
    action: "delete",
    possession: "any",
  })
  async deleteMigration(
    @graphql.Args() args: DeleteMigrationArgs
  ): Promise<Migration | null> {
    try {
      return await this.service.deleteMigration(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
