/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AcademicyearService } from "../academicyear.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AcademicyearCreateInput } from "./AcademicyearCreateInput";
import { Academicyear } from "./Academicyear";
import { AcademicyearFindManyArgs } from "./AcademicyearFindManyArgs";
import { AcademicyearWhereUniqueInput } from "./AcademicyearWhereUniqueInput";
import { AcademicyearUpdateInput } from "./AcademicyearUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AcademicyearControllerBase {
  constructor(
    protected readonly service: AcademicyearService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Academicyear })
  @nestAccessControl.UseRoles({
    resource: "Academicyear",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAcademicyear(
    @common.Body() data: AcademicyearCreateInput
  ): Promise<Academicyear> {
    return await this.service.createAcademicyear({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        status: true,
        updatedAt: true,
        yearEnd: true,
        yearStart: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Academicyear] })
  @ApiNestedQuery(AcademicyearFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Academicyear",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async academicyears(@common.Req() request: Request): Promise<Academicyear[]> {
    const args = plainToClass(AcademicyearFindManyArgs, request.query);
    return this.service.academicyears({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        status: true,
        updatedAt: true,
        yearEnd: true,
        yearStart: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Academicyear })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Academicyear",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async academicyear(
    @common.Param() params: AcademicyearWhereUniqueInput
  ): Promise<Academicyear | null> {
    const result = await this.service.academicyear({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        status: true,
        updatedAt: true,
        yearEnd: true,
        yearStart: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Academicyear })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Academicyear",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAcademicyear(
    @common.Param() params: AcademicyearWhereUniqueInput,
    @common.Body() data: AcademicyearUpdateInput
  ): Promise<Academicyear | null> {
    try {
      return await this.service.updateAcademicyear({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          status: true,
          updatedAt: true,
          yearEnd: true,
          yearStart: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Academicyear })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Academicyear",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAcademicyear(
    @common.Param() params: AcademicyearWhereUniqueInput
  ): Promise<Academicyear | null> {
    try {
      return await this.service.deleteAcademicyear({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          status: true,
          updatedAt: true,
          yearEnd: true,
          yearStart: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
