/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, PersonalAccessToken } from "@prisma/client";

export class PersonalAccessTokenServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.PersonalAccessTokenCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.PersonalAccessTokenCountArgs>
  ): Promise<number> {
    return this.prisma.personalAccessToken.count(args);
  }

  async personalAccessTokens<T extends Prisma.PersonalAccessTokenFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.PersonalAccessTokenFindManyArgs>
  ): Promise<PersonalAccessToken[]> {
    return this.prisma.personalAccessToken.findMany(args);
  }
  async personalAccessToken<T extends Prisma.PersonalAccessTokenFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PersonalAccessTokenFindUniqueArgs>
  ): Promise<PersonalAccessToken | null> {
    return this.prisma.personalAccessToken.findUnique(args);
  }
  async createPersonalAccessToken<
    T extends Prisma.PersonalAccessTokenCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.PersonalAccessTokenCreateArgs>
  ): Promise<PersonalAccessToken> {
    return this.prisma.personalAccessToken.create<T>(args);
  }
  async updatePersonalAccessToken<
    T extends Prisma.PersonalAccessTokenUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.PersonalAccessTokenUpdateArgs>
  ): Promise<PersonalAccessToken> {
    return this.prisma.personalAccessToken.update<T>(args);
  }
  async deletePersonalAccessToken<
    T extends Prisma.PersonalAccessTokenDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.PersonalAccessTokenDeleteArgs>
  ): Promise<PersonalAccessToken> {
    return this.prisma.personalAccessToken.delete(args);
  }
}
