/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PersonalAccessTokenService } from "../personalAccessToken.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PersonalAccessTokenCreateInput } from "./PersonalAccessTokenCreateInput";
import { PersonalAccessToken } from "./PersonalAccessToken";
import { PersonalAccessTokenFindManyArgs } from "./PersonalAccessTokenFindManyArgs";
import { PersonalAccessTokenWhereUniqueInput } from "./PersonalAccessTokenWhereUniqueInput";
import { PersonalAccessTokenUpdateInput } from "./PersonalAccessTokenUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PersonalAccessTokenControllerBase {
  constructor(
    protected readonly service: PersonalAccessTokenService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PersonalAccessToken })
  @nestAccessControl.UseRoles({
    resource: "PersonalAccessToken",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPersonalAccessToken(
    @common.Body() data: PersonalAccessTokenCreateInput
  ): Promise<PersonalAccessToken> {
    return await this.service.createPersonalAccessToken({
      data: data,
      select: {
        abilities: true,
        createdAt: true,
        expiresAt: true,
        id: true,
        lastUsedAt: true,
        name: true,
        token: true,
        tokenableId: true,
        tokenableType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PersonalAccessToken] })
  @ApiNestedQuery(PersonalAccessTokenFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PersonalAccessToken",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async personalAccessTokens(
    @common.Req() request: Request
  ): Promise<PersonalAccessToken[]> {
    const args = plainToClass(PersonalAccessTokenFindManyArgs, request.query);
    return this.service.personalAccessTokens({
      ...args,
      select: {
        abilities: true,
        createdAt: true,
        expiresAt: true,
        id: true,
        lastUsedAt: true,
        name: true,
        token: true,
        tokenableId: true,
        tokenableType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PersonalAccessToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PersonalAccessToken",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async personalAccessToken(
    @common.Param() params: PersonalAccessTokenWhereUniqueInput
  ): Promise<PersonalAccessToken | null> {
    const result = await this.service.personalAccessToken({
      where: params,
      select: {
        abilities: true,
        createdAt: true,
        expiresAt: true,
        id: true,
        lastUsedAt: true,
        name: true,
        token: true,
        tokenableId: true,
        tokenableType: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PersonalAccessToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PersonalAccessToken",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePersonalAccessToken(
    @common.Param() params: PersonalAccessTokenWhereUniqueInput,
    @common.Body() data: PersonalAccessTokenUpdateInput
  ): Promise<PersonalAccessToken | null> {
    try {
      return await this.service.updatePersonalAccessToken({
        where: params,
        data: data,
        select: {
          abilities: true,
          createdAt: true,
          expiresAt: true,
          id: true,
          lastUsedAt: true,
          name: true,
          token: true,
          tokenableId: true,
          tokenableType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PersonalAccessToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PersonalAccessToken",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePersonalAccessToken(
    @common.Param() params: PersonalAccessTokenWhereUniqueInput
  ): Promise<PersonalAccessToken | null> {
    try {
      return await this.service.deletePersonalAccessToken({
        where: params,
        select: {
          abilities: true,
          createdAt: true,
          expiresAt: true,
          id: true,
          lastUsedAt: true,
          name: true,
          token: true,
          tokenableId: true,
          tokenableType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
