/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Teacher } from "@prisma/client";

export class TeacherServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.TeacherCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.TeacherCountArgs>
  ): Promise<number> {
    return this.prisma.teacher.count(args);
  }

  async teachers<T extends Prisma.TeacherFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.TeacherFindManyArgs>
  ): Promise<Teacher[]> {
    return this.prisma.teacher.findMany(args);
  }
  async teacher<T extends Prisma.TeacherFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TeacherFindUniqueArgs>
  ): Promise<Teacher | null> {
    return this.prisma.teacher.findUnique(args);
  }
  async createTeacher<T extends Prisma.TeacherCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TeacherCreateArgs>
  ): Promise<Teacher> {
    return this.prisma.teacher.create<T>(args);
  }
  async updateTeacher<T extends Prisma.TeacherUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TeacherUpdateArgs>
  ): Promise<Teacher> {
    return this.prisma.teacher.update<T>(args);
  }
  async deleteTeacher<T extends Prisma.TeacherDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.TeacherDeleteArgs>
  ): Promise<Teacher> {
    return this.prisma.teacher.delete(args);
  }
}
