/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ClassroomService } from "../classroom.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ClassroomCreateInput } from "./ClassroomCreateInput";
import { Classroom } from "./Classroom";
import { ClassroomFindManyArgs } from "./ClassroomFindManyArgs";
import { ClassroomWhereUniqueInput } from "./ClassroomWhereUniqueInput";
import { ClassroomUpdateInput } from "./ClassroomUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ClassroomControllerBase {
  constructor(
    protected readonly service: ClassroomService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Classroom })
  @nestAccessControl.UseRoles({
    resource: "Classroom",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createClassroom(
    @common.Body() data: ClassroomCreateInput
  ): Promise<Classroom> {
    return await this.service.createClassroom({
      data: data,
      select: {
        academicyearsId: true,
        createdAt: true,
        enterprisesId: true,
        id: true,
        name: true,
        shortName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Classroom] })
  @ApiNestedQuery(ClassroomFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Classroom",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async classrooms(@common.Req() request: Request): Promise<Classroom[]> {
    const args = plainToClass(ClassroomFindManyArgs, request.query);
    return this.service.classrooms({
      ...args,
      select: {
        academicyearsId: true,
        createdAt: true,
        enterprisesId: true,
        id: true,
        name: true,
        shortName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Classroom })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Classroom",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async classroom(
    @common.Param() params: ClassroomWhereUniqueInput
  ): Promise<Classroom | null> {
    const result = await this.service.classroom({
      where: params,
      select: {
        academicyearsId: true,
        createdAt: true,
        enterprisesId: true,
        id: true,
        name: true,
        shortName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Classroom })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Classroom",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateClassroom(
    @common.Param() params: ClassroomWhereUniqueInput,
    @common.Body() data: ClassroomUpdateInput
  ): Promise<Classroom | null> {
    try {
      return await this.service.updateClassroom({
        where: params,
        data: data,
        select: {
          academicyearsId: true,
          createdAt: true,
          enterprisesId: true,
          id: true,
          name: true,
          shortName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Classroom })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Classroom",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteClassroom(
    @common.Param() params: ClassroomWhereUniqueInput
  ): Promise<Classroom | null> {
    try {
      return await this.service.deleteClassroom({
        where: params,
        select: {
          academicyearsId: true,
          createdAt: true,
          enterprisesId: true,
          id: true,
          name: true,
          shortName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
