/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TeachersAttendeeService } from "../teachersAttendee.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TeachersAttendeeCreateInput } from "./TeachersAttendeeCreateInput";
import { TeachersAttendee } from "./TeachersAttendee";
import { TeachersAttendeeFindManyArgs } from "./TeachersAttendeeFindManyArgs";
import { TeachersAttendeeWhereUniqueInput } from "./TeachersAttendeeWhereUniqueInput";
import { TeachersAttendeeUpdateInput } from "./TeachersAttendeeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TeachersAttendeeControllerBase {
  constructor(
    protected readonly service: TeachersAttendeeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TeachersAttendee })
  @nestAccessControl.UseRoles({
    resource: "TeachersAttendee",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTeachersAttendee(
    @common.Body() data: TeachersAttendeeCreateInput
  ): Promise<TeachersAttendee> {
    return await this.service.createTeachersAttendee({
      data: data,
      select: {
        academicyearsId: true,
        createdAt: true,
        date: true,
        id: true,
        teacherId: true,
        timeOfAttendance: true,
        timeOfDeparture: true,
        type: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TeachersAttendee] })
  @ApiNestedQuery(TeachersAttendeeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TeachersAttendee",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async teachersAttendees(
    @common.Req() request: Request
  ): Promise<TeachersAttendee[]> {
    const args = plainToClass(TeachersAttendeeFindManyArgs, request.query);
    return this.service.teachersAttendees({
      ...args,
      select: {
        academicyearsId: true,
        createdAt: true,
        date: true,
        id: true,
        teacherId: true,
        timeOfAttendance: true,
        timeOfDeparture: true,
        type: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TeachersAttendee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TeachersAttendee",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async teachersAttendee(
    @common.Param() params: TeachersAttendeeWhereUniqueInput
  ): Promise<TeachersAttendee | null> {
    const result = await this.service.teachersAttendee({
      where: params,
      select: {
        academicyearsId: true,
        createdAt: true,
        date: true,
        id: true,
        teacherId: true,
        timeOfAttendance: true,
        timeOfDeparture: true,
        type: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TeachersAttendee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TeachersAttendee",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTeachersAttendee(
    @common.Param() params: TeachersAttendeeWhereUniqueInput,
    @common.Body() data: TeachersAttendeeUpdateInput
  ): Promise<TeachersAttendee | null> {
    try {
      return await this.service.updateTeachersAttendee({
        where: params,
        data: data,
        select: {
          academicyearsId: true,
          createdAt: true,
          date: true,
          id: true,
          teacherId: true,
          timeOfAttendance: true,
          timeOfDeparture: true,
          type: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TeachersAttendee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TeachersAttendee",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTeachersAttendee(
    @common.Param() params: TeachersAttendeeWhereUniqueInput
  ): Promise<TeachersAttendee | null> {
    try {
      return await this.service.deleteTeachersAttendee({
        where: params,
        select: {
          academicyearsId: true,
          createdAt: true,
          date: true,
          id: true,
          teacherId: true,
          timeOfAttendance: true,
          timeOfDeparture: true,
          type: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
