/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AcademicperiodService } from "../academicperiod.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AcademicperiodCreateInput } from "./AcademicperiodCreateInput";
import { Academicperiod } from "./Academicperiod";
import { AcademicperiodFindManyArgs } from "./AcademicperiodFindManyArgs";
import { AcademicperiodWhereUniqueInput } from "./AcademicperiodWhereUniqueInput";
import { AcademicperiodUpdateInput } from "./AcademicperiodUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AcademicperiodControllerBase {
  constructor(
    protected readonly service: AcademicperiodService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Academicperiod })
  @nestAccessControl.UseRoles({
    resource: "Academicperiod",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAcademicperiod(
    @common.Body() data: AcademicperiodCreateInput
  ): Promise<Academicperiod> {
    return await this.service.createAcademicperiod({
      data: data,
      select: {
        academicyearsId: true,
        createdAt: true,
        dayCount: true,
        description: true,
        id: true,
        name: true,
        periodEnd: true,
        periodStart: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Academicperiod] })
  @ApiNestedQuery(AcademicperiodFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Academicperiod",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async academicperiods(
    @common.Req() request: Request
  ): Promise<Academicperiod[]> {
    const args = plainToClass(AcademicperiodFindManyArgs, request.query);
    return this.service.academicperiods({
      ...args,
      select: {
        academicyearsId: true,
        createdAt: true,
        dayCount: true,
        description: true,
        id: true,
        name: true,
        periodEnd: true,
        periodStart: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Academicperiod })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Academicperiod",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async academicperiod(
    @common.Param() params: AcademicperiodWhereUniqueInput
  ): Promise<Academicperiod | null> {
    const result = await this.service.academicperiod({
      where: params,
      select: {
        academicyearsId: true,
        createdAt: true,
        dayCount: true,
        description: true,
        id: true,
        name: true,
        periodEnd: true,
        periodStart: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Academicperiod })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Academicperiod",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAcademicperiod(
    @common.Param() params: AcademicperiodWhereUniqueInput,
    @common.Body() data: AcademicperiodUpdateInput
  ): Promise<Academicperiod | null> {
    try {
      return await this.service.updateAcademicperiod({
        where: params,
        data: data,
        select: {
          academicyearsId: true,
          createdAt: true,
          dayCount: true,
          description: true,
          id: true,
          name: true,
          periodEnd: true,
          periodStart: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Academicperiod })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Academicperiod",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAcademicperiod(
    @common.Param() params: AcademicperiodWhereUniqueInput
  ): Promise<Academicperiod | null> {
    try {
      return await this.service.deleteAcademicperiod({
        where: params,
        select: {
          academicyearsId: true,
          createdAt: true,
          dayCount: true,
          description: true,
          id: true,
          name: true,
          periodEnd: true,
          periodStart: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
