/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserModelService } from "../userModel.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserModelCreateInput } from "./UserModelCreateInput";
import { UserModel } from "./UserModel";
import { UserModelFindManyArgs } from "./UserModelFindManyArgs";
import { UserModelWhereUniqueInput } from "./UserModelWhereUniqueInput";
import { UserModelUpdateInput } from "./UserModelUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserModelControllerBase {
  constructor(
    protected readonly service: UserModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserModel })
  @nestAccessControl.UseRoles({
    resource: "UserModel",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUserModel(
    @common.Body() data: UserModelCreateInput
  ): Promise<UserModel> {
    return await this.service.createUserModel({
      data: data,
      select: {
        createdAt: true,
        email: true,
        emailVerifiedAt: true,
        id: true,
        name: true,
        password: true,
        rememberToken: true,
        serialCode: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserModel] })
  @ApiNestedQuery(UserModelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserModel",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userModels(@common.Req() request: Request): Promise<UserModel[]> {
    const args = plainToClass(UserModelFindManyArgs, request.query);
    return this.service.userModels({
      ...args,
      select: {
        createdAt: true,
        email: true,
        emailVerifiedAt: true,
        id: true,
        name: true,
        password: true,
        rememberToken: true,
        serialCode: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserModel",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userModel(
    @common.Param() params: UserModelWhereUniqueInput
  ): Promise<UserModel | null> {
    const result = await this.service.userModel({
      where: params,
      select: {
        createdAt: true,
        email: true,
        emailVerifiedAt: true,
        id: true,
        name: true,
        password: true,
        rememberToken: true,
        serialCode: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserModel",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUserModel(
    @common.Param() params: UserModelWhereUniqueInput,
    @common.Body() data: UserModelUpdateInput
  ): Promise<UserModel | null> {
    try {
      return await this.service.updateUserModel({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          emailVerifiedAt: true,
          id: true,
          name: true,
          password: true,
          rememberToken: true,
          serialCode: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserModel",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserModel(
    @common.Param() params: UserModelWhereUniqueInput
  ): Promise<UserModel | null> {
    try {
      return await this.service.deleteUserModel({
        where: params,
        select: {
          createdAt: true,
          email: true,
          emailVerifiedAt: true,
          id: true,
          name: true,
          password: true,
          rememberToken: true,
          serialCode: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
