/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TeachersPaymentService } from "../teachersPayment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TeachersPaymentCreateInput } from "./TeachersPaymentCreateInput";
import { TeachersPayment } from "./TeachersPayment";
import { TeachersPaymentFindManyArgs } from "./TeachersPaymentFindManyArgs";
import { TeachersPaymentWhereUniqueInput } from "./TeachersPaymentWhereUniqueInput";
import { TeachersPaymentUpdateInput } from "./TeachersPaymentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TeachersPaymentControllerBase {
  constructor(
    protected readonly service: TeachersPaymentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TeachersPayment })
  @nestAccessControl.UseRoles({
    resource: "TeachersPayment",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTeachersPayment(
    @common.Body() data: TeachersPaymentCreateInput
  ): Promise<TeachersPayment> {
    return await this.service.createTeachersPayment({
      data: data,
      select: {
        academicyearsId: true,
        createdAt: true,
        description: true,
        id: true,
        payment: true,
        paymentDate: true,
        payment_type: true,
        teacherId: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TeachersPayment] })
  @ApiNestedQuery(TeachersPaymentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TeachersPayment",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async teachersPayments(
    @common.Req() request: Request
  ): Promise<TeachersPayment[]> {
    const args = plainToClass(TeachersPaymentFindManyArgs, request.query);
    return this.service.teachersPayments({
      ...args,
      select: {
        academicyearsId: true,
        createdAt: true,
        description: true,
        id: true,
        payment: true,
        paymentDate: true,
        payment_type: true,
        teacherId: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TeachersPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TeachersPayment",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async teachersPayment(
    @common.Param() params: TeachersPaymentWhereUniqueInput
  ): Promise<TeachersPayment | null> {
    const result = await this.service.teachersPayment({
      where: params,
      select: {
        academicyearsId: true,
        createdAt: true,
        description: true,
        id: true,
        payment: true,
        paymentDate: true,
        payment_type: true,
        teacherId: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TeachersPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TeachersPayment",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTeachersPayment(
    @common.Param() params: TeachersPaymentWhereUniqueInput,
    @common.Body() data: TeachersPaymentUpdateInput
  ): Promise<TeachersPayment | null> {
    try {
      return await this.service.updateTeachersPayment({
        where: params,
        data: data,
        select: {
          academicyearsId: true,
          createdAt: true,
          description: true,
          id: true,
          payment: true,
          paymentDate: true,
          payment_type: true,
          teacherId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TeachersPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TeachersPayment",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTeachersPayment(
    @common.Param() params: TeachersPaymentWhereUniqueInput
  ): Promise<TeachersPayment | null> {
    try {
      return await this.service.deleteTeachersPayment({
        where: params,
        select: {
          academicyearsId: true,
          createdAt: true,
          description: true,
          id: true,
          payment: true,
          paymentDate: true,
          payment_type: true,
          teacherId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
